name: Lint
on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.16]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
